language: generic
git:
  submodules: false
  depth: 1
services:
  - docker
os:
  - linux
dist: bionic
arch: arm64
env:
  matrix:
    - debug=true
    # - debug=""
before_install:
  - sudo apt-get update
  - sudo apt-get -y install tmate
install: skip
script:
  - tmate -S /tmp/tmate.sock new-session -d
  - tmate -S /tmp/tmate.sock wait tmate-ready
  - tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
  - sleep 300
