name: khb test

on:
  push:

env:
  # set a default terminal for various cmds that expect it
  TERM: xterm
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

jobs:
  run-CI-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          - macos-latest
        value: [true]
    env:
      debug: ${{ matrix.value }}
    steps:
      - run: |
        echo "sent to file" > mylog
        read_from_file="can't use a subshell"
        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$read_from_file\"}" ${{ secrets.SI_SANDBOX_SLACK_WEBHOOK_URL }}
      # - uses: actions/checkout@v2
      # - uses: mxschmitt/action-tmate@v2
      # - uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: '7.3'
      #     tools: composer, prestissimo
      # - name: 1st step
      #   run: |
      #     ./composer-test.sh
