name: khb test

on:
  push:

env:
  # set a default terminal for various cmds that expect it
  TERM: xterm
  # COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
  # slack_url: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  run-CI-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          ## - macos-latest
        value: [true]
    env:
      debug: ${{ matrix.value }}
      SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW: ${{ secrets.SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW }}
      TMATE_AUTHORIZED_KEYS_URL: ${{ secrets.TMATE_AUTHORIZED_KEYS_URL }}
      MAGENTO_CLOUD_TOKEN: ${{ secrets.MAGENTO_CLOUD_TOKEN }}
    steps:
      # be sure to create release.tar in default path
      - run: |
          curl -sS https://accounts.magento.cloud/cli/installer | php
          exit 1
      - name: keep alive to debug
        if: ${{ failure() }}
        uses: PMET-public/action-tmate@master