name: khb test

on:
  push:

env:
  # set a default terminal for various cmds that expect it
  TERM: xterm
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
  # slack_url: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  run-CI-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
        value: [true]
    env:
      debug: ${{ matrix.value }}
      SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW: ${{ secrets.SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW }}
      TMATE_AUTHORIZED_KEYS_URL: ${{ secrets.TMATE_AUTHORIZED_KEYS_URL }}
    steps:
      - run: |
          echo "hi there" > mylog
      # read_from_file="$(<mylog)"
      # curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"private\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
      # - uses: actions/checkout@v2
      # - uses: mxschmitt/action-tmate@v2
      # - uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: '7.3'
      #     tools: composer, prestissimo
      # - name: 1st step
      #   run: |
      #     ./composer-test.sh
      - run: |
          exit 1
      - name: keepalive to debug
        if: ${{ failure() }}
        uses: PMET-public/action-tmate@master